INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Пушкин', 'Золотой ключик', 1988);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('notAvailable', 'Есенин', 'Ростов-на-Дону', 1997);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Левковский С.А.', 'Основы MYSQL', 2016);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Левковский С.А.', 'Как стать программистом', 2016);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Tolkien', 'The_Lord_of_the_Rings', 2003);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('notAvailable', 'Есенин', 'Есенин', 2006);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Лермонтов', 'Лермонтов', 2000);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('notAvailable', 'zxcvb', 'zxcvb', 1234);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('notAvailable', 'aaaa', 'aaaa', 1111);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Тургенев', 'Книга2', 1324);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Tolkien', 'LOTR', 2016);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Tolkien', 'LOTR2', 2004);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Тютчев', 'Тютчев', 2003);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('notAvailable', 'Галустян', 'Галустян', 2016);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('notAvailable', 'awd', 'wadaw', 1231);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('notAvailable', 'waaw', 'wasdaw', 2141);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('notAvailable', 'Лермонтов', 'Лермонтов', 2017);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Блинов И.Н.', 'JAVA. МЕТОДЫ ПРОГРАММИРОВАНИЯ', 2013);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Craig Walls', 'Spring in Action, Fourth Edition', 2014);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Christian Bauer, Gavin King, and Gary Gregory', 'Java Persistence with Hibernate, Second Edition', 2015);
INSERT INTO oxothukdb.books (access, author, title, date) VALUES ('available', 'Левковский', 'Final', 2017);